name    : libedit
version : 3.1
release : 1
source  :
    - http://thrysoee.dk/editline/libedit-20150325-3.1.tar.gz : c88a5e4af83c5f40dda8455886ac98923a9c33125699742603a88a0253fcc8c5
license :
    - BSD
homepage: http://thrysoee.dk/editline/
summary : An autotool- and libtoolized port of the NetBSD Editline library
description: |
    This is an autotool- and libtoolized port of the NetBSD Editline library (libedit).
    This Berkeley-style licensed command line editor library provides generic line editing,
    history, and tokenization functions, similar to those found in GNU Readline.
setup: |
    %configure --enable-widec
build: |
    %make
install: |
    %make_install
rundeps:
    - ncurses
    - glibc
